config/routes.rb
Rails.application.routes.draw do

  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  resources :sites


  namespace :'api', defaults: {format: :json} do
    devise_scope :user do
      resource :session, only: [:create, :destroy]
    end

    resources :categories
    resources :portfolios
    resources :themes

    resources :jobs do
      resources :applicants
    end

    # match 'blog' => "posts#index",      :as => :blog  , via: [:get, :post]

    resources :posts do
      member do
        get :published
        get :unpublished
        get :user_profile
        put :like
        put :dislike
      end

      collection do
        get :blog_posts
      end

      resources :contacts
      resources :comments

    end
  end
  # match 'blog' => "posts#index",      :as => :blog  , via: [:get, :post]
# scope :api-old , defaults: { format: 'json' } do
  resources :themes
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks", registrations: "registrations"}


  resources :jobs do
    resources :applicants
  end

  resources :posts do
    member do
      get :published
      get :unpublished
      get :user_profile
      put :like
      put :dislike
    end
    collection do
      get :blog_posts
    end
    resources :contacts
    resources :comments
  end
  resources :portfolios

  root to: "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
    belongs_to :parent_category, :class_name => "Category"
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < Api::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    #@categories = Category.all
    @category = nil
    #@categories = Category.find(:all, :conditions => {:parent_id => nil } )
    render json: @categories = Category.all.where(parent_id: nil)

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    # Find the category belonging to the given id
    @category = Category.find(params[:id])

    # Grab all sub-categories
    render json: @categories = @category.subcategories

  end

  # GET /categories/new
  def new
    p params[:cat_id]
    @category = Category.new
    if !params[:cat_id].nil?
      main_cat = Category.find(params[:cat_id]) unless params[:cat_id].nil?
      @category.parent_id = main_cat.id
    end
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        if !@category.parent_id.nil?
          @category = Category.find(@category.parent_id)
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @category }
        end
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:parent_id, :name, :description)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    #@categories = Category.all
    @category = nil
    #@categories = Category.find(:all, :conditions => {:parent_id => nil } )
    @categories = Category.all.where(parent_id: nil)

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    # Find the category belonging to the given id
    @category = Category.find(params[:id])

    # Grab all sub-categories
    @categories = @category.subcategories
    # We want to reuse the index renderer:
    # respond_to do |format|
    #   format.html { render :action => :index }
    # end
  end

  # GET /categories/new
  def new
    p params[:cat_id]
    @category = Category.new
    if !params[:cat_id].nil?
      main_cat = Category.find(params[:cat_id]) unless params[:cat_id].nil?
      @category.parent_id = main_cat.id
    end
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        if !@category.parent_id.nil?
          @category = Category.find(@category.parent_id)
          format.html { redirect_to @category, notice: 'Category was successfully created.' }0
          format.json { render :show, status: :created, location: @category }
        else
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @category }
        end
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:parent_id, :name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :parent_id %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1><%= @category.nil? ? 'Main categories' : category.name %></h1>
<h3>
  <%= link_to 'Add New Category', new_category_path %>
</h3>

<table class="sortable">
      <thead>
        <tr>
          <th>Category Name</th>
          <th>Description</th>
          <th>Edit </th>
          <th>Delete </th>
          <th>Date Modified</th>
          <th>Add New SubCategory</th>
        </tr>
      </thead>
      <tbody>

<% @categories.each do |category| %>
<tr>
  <td><%= link_to category.name, category_path(category) %></td>
  <td><%= category.description %></td>
  <td><%= link_to 'Edit', edit_category_path(category)%></td>
  <td><%= link_to 'Destroy', category_path(category), :confirm => 'Are you sure?', :method => :delete %></td>
  <td><%= category.updated_at %></td>
  <td><%= link_to 'New sub-category', new_category_path(:cat_id=>category.id) %></td>
</tr>
<% end %>
 </tbody>
</table>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<table>
<h3>
	<div >
	<%= link_to 'New sub-category', new_category_path(:cat_id=>@category.id) %>
</div>
<div style="float:right">
	<%= link_to 'Back', categories_path %>
</div>
</h3>
<table class="sortable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Edit </th>
          <th>Delete </th>
          <th>Date Modified</th
        </tr>
      </thead>
      <tbody>

<% @categories.each do |subcategory| %>
<tr>
  <td><%= subcategory.name %></td>
  <td><%= subcategory.description %></td>
  <td><%= link_to 'Edit', edit_category_path(subcategory)%></td>
  <td><%= link_to 'Destroy', category_path(subcategory), :confirm => 'Are you sure?', :method => :delete %></td>
  <td><%= subcategory.updated_at %></td>
</tr>
<% end %>
 </tbody>
</table>